### ISSUE TITLE
pinia版本

### ISSUE THREAD

**Issue by Mrzhugq** [Sjj1024/uniapp-vue3#1]
`
    "pinia": "2.0.27",
    "uview-plus": "^3.1.19",
    "vue": "3.2.45",
    "vue-i18n": "^9.1.9"
`
把 pinia 和 vue 前面的^去掉就，使用npm启动就不会报错了

**Comment by Mrzhugq** [comment]
还有我想问下，为啥我复制官网的代码样式和官网的一样呢？我的button撑满了，而且icon也不显示
![QQ截图20240106223703](https://github.com/Sjj1024/uniapp-vue3/assets/84071063/e1d7f6f5-77a4-4a83-b546-02861d9aeca0)

**Comment by Sjj1024** [comment]
样式问题自己慢慢调
